spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/haritpane_database
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

server:
  port: 8888



aws:
  region: ${AWS_S3_REGION}
  bucket-name: ${AWS_S3_BUCKET_NAME}
  access-key: ${AWS_ACCESS_KEY_ID}
  secret-key: ${AWS_SECRET_ACCESS_KEY}