spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/haritpane_database
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: mdhasrat233222@gmail.com
    password: dvjt hlka wyqk aqrd

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

server:
  port: 8888

jwt:
  secret: 0uP4fQz7vM4vQv8HnQ5hN6t5W2x9b8M3R2Q1S5T7Y9K8L6N4P3Q2R1T8U7V6W5X4
  expiration: 3600000



aws:
  region: ${AWS_S3_REGION}
  bucket-name: ${AWS_S3_BUCKET_NAME}
  access-key: ${AWS_ACCESS_KEY_ID}
  secret-key: ${AWS_SECRET_ACCESS_KEY}